-- Create team_strength_of_record table if it doesn't exist
CREATE TABLE IF NOT EXISTS team_strength_of_record (
  id BIGSERIAL PRIMARY KEY,
  rank_id INTEGER NOT NULL,
  team_name TEXT NOT NULL,
  conference TEXT,
  sor_rank INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(team_name)
);

CREATE INDEX IF NOT EXISTS idx_team_strength_of_record_team_name ON team_strength_of_record(team_name);
CREATE INDEX IF NOT EXISTS idx_team_strength_of_record_rank_id ON team_strength_of_record(rank_id);
CREATE INDEX IF NOT EXISTS idx_team_strength_of_record_sor_rank ON team_strength_of_record(sor_rank);

-- Enable RLS
ALTER TABLE team_strength_of_record ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
    AND tablename = 'team_strength_of_record' 
    AND policyname = 'Allow public read access'
  ) THEN
    CREATE POLICY "Allow public read access" ON team_strength_of_record
      FOR SELECT
      USING (true);
  END IF;
END $$;

-- Insert/Update the full list of teams
INSERT INTO team_strength_of_record (rank_id, team_name, conference, sor_rank) VALUES
(1, 'Indiana Hoosiers', 'Big Ten', 2),
(2, 'Texas A&M Aggies', 'SEC', 10),
(3, 'Ohio State Buckeyes', 'Big Ten', 16),
(4, 'Georgia Bulldogs', 'SEC', 6),
(5, 'Oregon Ducks', 'Big Ten', 12),
(6, 'Ole Miss Rebels', 'SEC', 23),
(7, 'BYU Cougars', 'Big 12', 35),
(8, 'Oklahoma Sooners', 'SEC', 15),
(9, 'Alabama Crimson Tide', 'SEC', 5),
(10, 'Texas Tech Red Raiders', 'Big 12', 17),
(11, 'Texas Longhorns', 'SEC', 10),
(12, 'Vanderbilt Commodores', 'SEC', 12),
(13, 'Notre Dame Fighting Irish', 'FBS Indep.', 41),
(14, 'Michigan Wolverines', 'Big Ten', 25),
(15, 'Utah Utes', 'Big 12', 39),
(16, 'Miami Hurricanes', 'ACC', 15),
(17, 'USC Trojans', 'Big Ten', 12),
(18, 'Tennessee Volunteers', 'SEC', 47),
(19, 'Navy Midshipmen', 'American', 17),
(20, 'Iowa Hawkeyes', 'Big Ten', 37),
(21, 'LSU Tigers', 'SEC', 32),
(22, 'James Madison Dukes', 'Sun Belt', 70),
(23, 'Tulane Green Wave', 'American', 56),
(24, 'North Texas Mean Green', 'American', 19),
(25, 'Arizona Wildcats', 'Big 12', 25),
(26, 'Washington Huskies', 'Big Ten', 33),
(27, 'Missouri Tigers', 'SEC', 123),
(28, 'Virginia Cavaliers', 'ACC', 55),
(29, 'Illinois Fighting Illini', 'Big Ten', 71),
(30, 'Georgia Tech Yellow Jackets', 'ACC', 36),
(31, 'Arizona State Sun Devils', 'Big 12', 36),
(32, 'Pittsburgh Panthers', 'ACC', 58),
(33, 'South Florida Bulls', 'American', 22),
(34, 'SMU Mustangs', 'ACC', 23),
(35, 'TCU Horned Frogs', 'Big 12', 40),
(36, 'Houston Cougars', 'Big 12', 61),
(37, 'Iowa State Cyclones', 'Big 12', 43),
(38, 'Wake Forest Demon Deacons', 'ACC', 60),
(39, 'Louisville Cardinals', 'ACC', 40),
(40, 'Cincinnati Bearcats', 'Big 12', 30),
(41, 'UNLV Rebels', 'Mountain West', 11),
(42, 'New Mexico Lobos', 'Mountain West', 107),
(43, 'Kentucky Wildcats', 'SEC', 34),
(44, 'NC State Wolfpack', 'ACC', 50),
(45, 'Old Dominion Monarchs', 'Sun Belt', 49),
(46, 'Northwestern Wildcats', 'Big Ten', 56),
(47, 'Nebraska Cornhuskers', 'Big Ten', 63),
(48, 'Auburn Tigers', 'SEC', 53),
(49, 'Wisconsin Badgers', 'Big Ten', 42),
(50, 'Minnesota Golden Gophers', 'Big Ten', 78),
(51, 'Boise State Broncos', 'Mountain West', 38),
(52, 'Mississippi State Bulldogs', 'SEC', 50),
(53, 'Kennesaw State Owls', 'CUSA', 56),
(54, 'San Diego State Aztecs', 'Mountain West', 129),
(55, 'South Carolina Gamecocks', 'SEC', 42),
(56, 'Penn State Nittany Lions', 'Big Ten', 52),
(57, 'Florida Gators', 'SEC', 38),
(58, 'Rutgers Scarlet Knights', 'Big Ten', 8),
(59, 'Baylor Bears', 'Big 12', 78),
(60, 'Western Kentucky Hilltoppers', 'CUSA', 29),
(61, 'East Carolina Pirates', 'American', 80),
(62, 'Kansas State Wildcats', 'Big 12', 74),
(63, 'Clemson Tigers', 'ACC', 46),
(64, 'Duke Blue Devils', 'ACC', 26),
(65, 'Memphis Tigers', 'American', 46),
(66, 'Western Michigan Broncos', 'MAC', 46),
(67, 'UConn Huskies', 'FBS Indep.', 14),
(68, 'Florida State Seminoles', 'ACC', 53),
(69, 'Missouri State Bears', 'CUSA', 1),
(70, 'Ohio Bobcats', 'MAC', 119),
(71, 'UTSA Roadrunners', 'American', 30),
(72, 'Hawai''i Rainbow Warriors', 'Mountain West', 51),
(73, 'Washington State Cougars', 'Pac-12', 71),
(74, 'Kansas Jayhawks', 'Big 12', 52),
(75, 'Fresno State Bulldogs', 'Mountain West', 12),
(76, 'Troy Trojans', 'Sun Belt', 82),
(77, 'California Golden Bears', 'ACC', 91),
(78, 'Central Michigan Chippewas', 'MAC', 81),
(79, 'West Virginia Mountaineers', 'Big 12', 66),
(80, 'UCLA Bruins', 'Big Ten', 51),
(81, 'Toledo Rockets', 'MAC', 21),
(82, 'Stanford Cardinal', 'ACC', 5),
(83, 'UCF Knights', 'Big 12', 72),
(84, 'Coastal Carolina Chanticleers', 'Sun Belt', 17),
(85, 'Utah State Aggies', 'Mountain West', 38),
(86, 'Southern Miss Golden Eagles', 'Sun Belt', 2),
(87, 'Syracuse Orange', 'ACC', 97),
(88, 'Army Black Knights', 'American', 24),
(89, 'Maryland Terrapins', 'Big Ten', 86),
(90, 'Miami (OH) RedHawks', 'MAC', 38),
(91, 'Jacksonville State Gamecocks', 'CUSA', 99),
(92, 'Michigan State Spartans', 'Big Ten', 118),
(93, 'Arkansas Razorbacks', 'SEC', 71),
(94, 'Colorado Buffaloes', 'Big 12', 91),
(95, 'Florida International Panthers', 'CUSA', 43),
(96, 'Louisiana Tech Bulldogs', 'CUSA', 34),
(97, 'Virginia Tech Hokies', 'ACC', 55),
(98, 'Georgia Southern Eagles', 'Sun Belt', 72),
(99, 'Louisiana Ragin'' Cajuns', 'Sun Belt', 57),
(100, 'Rice Owls', 'American', 51),
(101, 'Temple Owls', 'American', 77),
(102, 'Texas State Bobcats', 'Sun Belt', 84),
(103, 'Marshall Thundering Herd', 'Sun Belt', 109),
(104, 'Purdue Boilermakers', 'Big Ten', 49),
(105, 'North Carolina Tar Heels', 'ACC', 110),
(106, 'Arkansas State Red Wolves', 'Sun Belt', 67),
(107, 'App State Mountaineers', 'Sun Belt', 135),
(108, 'Kent State Golden Flashes', 'MAC', 18),
(109, 'Florida Atlantic Owls', 'American', 46),
(110, 'Delaware Blue Hens', 'CUSA', 62),
(111, 'Tulsa Golden Hurricane', 'American', 89),
(112, 'Ball State Cardinals', 'MAC', 70),
(113, 'Wyoming Cowboys', 'Mountain West', 90),
(114, 'UAB Blazers', 'American', 35),
(115, 'South Alabama Jaguars', 'Sun Belt', 66),
(116, 'New Mexico State Aggies', 'CUSA', 51),
(117, 'Liberty Flames', 'CUSA', 101),
(118, 'Nevada Wolf Pack', 'Mountain West', 54),
(119, 'Air Force Falcons', 'Mountain West', 45),
(120, 'Akron Zips', 'MAC', 31),
(121, 'San José State Spartans', 'Mountain West', 50),
(122, 'UL Monroe Warhawks', 'Sun Belt', 92),
(123, 'Buffalo Bulls', 'MAC', 111),
(124, 'Oklahoma State Cowboys', 'Big 12', 114),
(125, 'Eastern Michigan Eagles', 'MAC', 92),
(126, 'Bowling Green Falcons', 'MAC', 81),
(127, 'Boston College Eagles', 'ACC', 99),
(128, 'Oregon State Beavers', 'Pac-12', 39),
(129, 'Colorado State Rams', 'Mountain West', 37),
(130, 'Northern Illinois Huskies', 'MAC', 9),
(131, 'Sam Houston Bearkats', 'CUSA', 52),
(132, 'Charlotte 49ers', 'American', 75),
(133, 'Georgia State Panthers', 'Sun Belt', 81),
(134, 'UTEP Miners', 'CUSA', 33),
(135, 'Middle Tennessee Blue Raiders', 'CUSA', 126),
(136, 'Massachusetts Minutemen', 'MAC', 136)
ON CONFLICT (team_name) DO UPDATE SET
  rank_id = EXCLUDED.rank_id,
  conference = EXCLUDED.conference,
  sor_rank = EXCLUDED.sor_rank,
  updated_at = NOW();

